spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mypet?useSSL=false&serverTimezone=UTC
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
server:
  port: 8081